### PR TITLE
Tell Cython that callbacks may raise exceptions.

### PR DESCRIPTION
**Pull request by ThomasWaldmann**

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
@Nikratio : created a PR from the branch for better review and testing.

**Review by Nikratio — APPROVED** [review]
Looks good to me.

**Comment by Nikratio** [comment]
...but when going with this solution, you should also revert https://github.com/libfuse/pyfuse3/pull/81/commits/783693c7986acc6c655be2df8ea6fe421e50dab9 (probably in the same commit).

**Comment by ThomasWaldmann** [comment]
OK, rebased onto current master, reverted that commit, squashed all together.

**Pull request merged**
