### PR TITLE
Release 3.2.2

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
main focus here is to get a new release that is cythonized with a current cython, so it will work on python 3.11 also.

also, pyfuse3 should be tested for all supported python versions and I got rid of travis-ci, using github actions now.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
@Nikratio Hmm, github actions seems not to run automatically here although there is a config for it in this PR.

I checked the settings I have access to, but didn't find anything there.

**Comment by ThomasWaldmann** [comment]
Guess you need to enable this via Settings -> Actions -> General

**Comment by sophie-h** [comment]
Is there any new release in sight? Newer Flatpak runtimes on Flathub come with Python 3.10 which does not work with the 3.2.1 package (undefined symbol: _PyGen_Sen)

**Comment by ThomasWaldmann** [comment]
Hmm, still no github actions CI running here.

But it runs in the source repo:

https://github.com/ThomasWaldmann/pyfuse3/actions/runs/3139614834

**Comment by ThomasWaldmann** [comment]
@sophie-h I'll try to make a new release from the code that is in master now.

**Comment by ThomasWaldmann** [comment]
@sophie-h see the 3.2.2 release on github releases page (and also on pypi).

It was cythonized with 0.29.30, which might be good enough, but we could also try 0.29.32 if not (forgot `pip install -U Cython`).

If you see any issue, please give feedback.

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/actions/runs/3140063281/jobs/5101083301 test with py311.

**Pull request merged**
